# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v .

    - name: Test
      run: go test .

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: gokvstore
        path: gokvstore


  release-project:
    name: Release binary to github releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: gokvstore
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Latest release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: gokvstore
          asset_name: gokvstore
          asset_content_type: application
